<?php
/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Magento\Framework\Escaper $escaper
 */

/** @var \Magento\Catalog\Helper\Output $_helper */
$_helper = $block->getData('outputHelper');
/** @var \Hibrido\Theme\ViewModel\ProductSlider $_productViewModel */
$_productViewModel = $block->getData('product_collection_view_model');
$_productCollection = $_productViewModel->getNewsProductsCollection();
?>

<div class="product-carousel row contained" data-mage-init='{"Magento_Theme/js/product-slickslider":{}}'>
    <h2><?= $escaper->escapeHtml(__('Lançamentos')) ?></h2>
    <div class="page-products">
        <div class="products wrapper grid products-grid">
            <ol class="products list items product-items slick-slider-product">
                <?php foreach ($_productCollection as $_product): ?>
                    <li class="item product product-item">
                        <div class="product-item-info"
                             id="product-item-info_<?= /* @noEscape */ $_product->getId() ?>">
                            <?php
                            $productImage = $block->getImage($_product, 'category_page_grid');
                            ?>
                            <a href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>"
                               class="product photo product-item-photo"
                               tabindex="-1">
                                <?= $productImage->toHtml() ?>
                            </a>
                            <div class="product details product-item-details">
                                <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
                                <strong class="product name product-item-name">
                                    <a class="product-item-link"
                                       href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>">
                                        <?=/* @noEscape */ $_helper->productAttribute($_product, $_product->getName(), 'name')?>
                                    </a>
                                </strong>
                                <?= /* @noEscape */ $block->getProductPrice($_product) ?>

                                <?= $block->getProductDetailsHtml($_product) ?>

                                <div class="product-item-inner">
                                    <div class="product actions product-item-actions">
                                        <div class="actions-primary">
                                            <?php if ($_product->isAvailable()):?>
                                                <div class="stock available">
                                                    <span><?= $escaper->escapeHtml(__('In stock')) ?></span></div>
                                            <?php else:?>
                                                <div class="stock unavailable">
                                                    <span><?= $escaper->escapeHtml(__('Out of stock')) ?></span></div>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ol>
        </div>
    </div>
</div>
